### ISSUE TITLE
piltide kadreerimine ja suuruste muutmine

### ISSUE THREAD

**Issue by mitselek** [i-b-c/KGS#114]
Praegune Kanuti piltide automaatika töötab alloleva konfiguratsiooni peal.
Kood, mis selle konfi realiseerib, asub https://github.com/mitselek/pildimaag

Meil on tarvis taasluua midagi sarnast, aga veid lihtsamat; me näiteks ei soovi renderdada piltidele tekste.
Et ülesanne oleks huvitavam, peab loogika olema kirjutatud mõnes uues keeles; ntx [Go](https://golang.org/doc/install).

```yaml
name: Saali pildimaag.
tasks:
  - name: Saali lavastuste karusselli ja galerii pildid
    source:
      definitions:
        - performance
      property: photo-original
    targets:
      - property: photo
        format: png
        fixWidth: 200
        fixHeight: 200
        crop: auto
        forceKeepInSync: true
        fileNamePrefix: ''
        fileNameSuffix: ' 200'
      - property: photo-medium
        format: jpg
        fixWidth: 350
        fixHeight: 350
        crop: center
        forceKeepInSync: true
        fileNamePrefix: ''
        fileNameSuffix: ' 350x350'
      - property: photo-gallery
        format: jpg
        maxWidth: 1400
        maxHeight: 700
        crop: center
        forceKeepInSync: true
        fileNamePrefix: ''
        fileNameSuffix: ''
  - name: Saali sündmuste karusselli ja galerii pildid
    source:
      definitions:
        - event
      property: photo-original
    targets:
      - property: photo
        format: png
        fixWidth: 200
        fixHeight: 200
        crop: auto
        forceKeepInSync: false
        fileNamePrefix: ''
        fileNameSuffix: ' 200'
      - property: photo-medium
        format: jpg
        fixWidth: 350
        fixHeight: 350
        crop: center
        forceKeepInSync: false
        fileNamePrefix: ''
        fileNameSuffix: ' 350x350'
      - property: photo-gallery
        format: jpg
        maxWidth: 1400
        maxHeight: 700
        crop: center
        forceKeepInSync: true
        fileNamePrefix: ''
        fileNameSuffix: ''
  - name: Saali magasini karusselli ja galerii pildid
    source:
      definitions:
        - echo
      property: photo-original
    targets:
      - property: photo
        format: png
        fixWidth: 200
        fixHeight: 200
        crop: auto
        forceKeepInSync: false
        fileNamePrefix: ''
        fileNameSuffix: ' 200x200'
      - property: photo-medium
        format: jpg
        fixWidth: 350
        fixHeight: 350
        crop: center
        forceKeepInSync: false
        fileNamePrefix: ''
        fileNameSuffix: ' 350x350'
      - property: photo-big
        format: jpg
        fixWidth: 1400
        crop: center
        forceKeepInSync: false
        fileNamePrefix: ''
        fileNameSuffix: ' 1400x'
```
